defaults: &defaults
  access_key_id: "AKIAJTES5EVRSQ4QAH3A"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "jobsuploadsdev"
test:
  <<: *defaults
  bucket: "myapp-test"
production:
  access_key_id: "AKIAJTES5EVRSQ4QAH3A"
  secret_access_key: "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"
  bucket: "jobsuploadsdev"