defaults: &defaults
  access_key_id: "AKIAIH3TTESUDNS6A5BQ"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "jobsuploadsdev"
test:
  <<: *defaults
  bucket: "myapp-test"
production:
  access_key_id: "AKIAIH3TTESUDNS6A5BQ"
  secret_access_key: "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"
  bucket: "jobsuploadsdev"